version: '2.2'
services:
  app:
    image: blog-app
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
        - /app/out
    ports:
      - "3000:3000"